global_costmap:
  plugins: 
    
    - {name: static_map, type: "costmap_2d::StaticLayer"}
    - {name: temp, type: "costmap_2d::ObstacleLayer"}
    # - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  robot_radius: 0.34
  temp:
    observation_sources: temp_sensor
    temp_sensor: {sensor_frame: temp_link, data_type: LaserScan, topic: /temp, marking: true, clearing: true, inf_is_valid: true, obstacle_range: 5.6, raytrace_range: 6.6}
  # obstacles:
  #   observation_sources: laser_scan_sensor
  #   laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true}
  #   obstacle_range: 10
  #   raytrace_range: 3.0
  #   track_unknown_space: true
  inflation:
    inflation_radius: 1.5
